[package]
name = "diesel_rust_db_ex"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.0", features = ["postgres"] }
dotenvy = "0.15"
tokio = { version = "1", features = ["full"] }
